# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f42bbfd362ab1325a25197f5394faba2647860d0a3dd159f662d2902f58d77aefa1e72680813fc562d8c3e19291c9e00fd5f76f38f81d3ed4ce6fe9451cbe5f

test:
  secret_key_base: eb1cbeff4963b8cadc50db472a09e017c67879df9817fd092c71acee003ecf1b6f3a7eb388d495990947c67d0bdc1e67bcd8cb6bc8c3697f19131309c9bf511b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
